{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "k-bot.serviceAccountName" . }}-role
rules:
  - apiGroups:
      - v1
    resources:
      - pods
      - services
      - pods/log
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k-bot.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k-bot.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "k-bot.serviceAccountName" . }}
    namespace: {{.Release.namespace}}
{{- end -}}