name: Publish
on: [push]
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          context: src
          name: efrat19/k-bot
          username: efrat19
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,amd64-${{ github.sha }}"
